#dev config
env = "dev"
port = 443

#sql config
[db]
client = "postgres"
host = "127.0.0.1"
port = 8888
database = "test_db"
user = "postgres"
password = ""

#redis config
[redis]
host = "127.0.0.1"
port = 5432
password = ""

#jwt
[jwt]
jwt_key = "key"
jwt_cookie =""


#sms
#[sms]







